import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

function embedAssets(): Plugin {
	return {
		name: "embed-assets",
		closeBundle() {
			const distDir = join(__dirname, "dist");
			const outputPath = join(__dirname, "generated/assets.ts");

			const assets: Record<string, { content: string; contentType: string }> =
				{};

			function walk(dir: string) {
				for (const entry of readdirSync(dir)) {
					const fullPath = join(dir, entry);
					const stat = statSync(fullPath);
					if (stat.isDirectory()) {
						walk(fullPath);
					} else {
						const relativePath = relative(distDir, fullPath);
						const content = readFileSync(fullPath);
						const contentType = getContentType(entry);
						assets[relativePath] = {
							content: content.toString("base64"),
							contentType,
						};
					}
				}
			}

			function getContentType(filename: string): string {
				const ext = filename.split(".").pop()?.toLowerCase();
				const types: Record<string, string> = {
					html: "text/html",
					js: "application/javascript",
					css: "text/css",
					json: "application/json",
					svg: "image/svg+xml",
					png: "image/png",
					ico: "image/x-icon",
				};
				return types[ext || ""] || "application/octet-stream";
			}

			walk(distDir);

			const code = `// Generated by vite build - do not edit
export const assets: Record<string, { content: string; contentType: string }> = ${JSON.stringify(assets, null, 2)};
`;

			writeFileSync(outputPath, code);
			console.log(`Generated assets.ts with ${Object.keys(assets).length} files`);
		},
	};
}

export default defineConfig({
	plugins: [tailwindcss(), react(), embedAssets()],
});
